workflows:
  ios-workflow:
    name: Abra Zylo iOS
    max_build_duration: 60
    working_directory: GuruAri_AbraZylo/GuruAri_AbraZylo/app_code/abra_zylo/abra_zylo
    integrations:
      app_store_connect: Abra App Store Key
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install pods
        script: find . -name "Podfile" -execdir pod install \;
      - name: Build IPA
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration