workflows:
  ios-workflow:
    name: Abra Zylo iOS
    max_build_duration: 60
    working_directory: GuruAri_AbraZylo/GuruAri_AbraZylo/app_code/abra_zylo/abra_zylo/abra_zylo_opencart_builder
    integrations:
      app_store_connect: Abra App Store Key
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.abralogistic.abrazylo
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install pods
        script: find . -name "Podfile" -execdir pod install \;
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files com.abralogistic.abrazylo --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Build IPA
        script: flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
  - build/ios/ipa/*.ipa
  - "**/*.ipa"
  - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false